# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('pim-sm-example', ['point-to-point', 'internet','pim-sm'])
    obj.source = 'pim-sm-example.cc'

