# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('pimsm', ['core','csma','internet','applications'])
    module.source = [
        'model/pimsm.cc',
        'model/pimsm-header.cc',
        'model/pim-multicast-forwarding-cache.cc',
        'helper/pimsm-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('pimsm')
    module_test.source = [
        'test/pimsm-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'pimsm'
    headers.source = [
        'model/pimsm.h',
        'model/pimsm-header.h',
        'model/pim-multicast-forwarding-cache.h',
        'helper/pimsm-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

