# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('pimsm-example', ['point-to-point', 'internet','pimsm'])
    obj.source = 'pimsm-example.cc'

